DROP TABLE IF EXISTS pokemons;

CREATE TABLE pokemons (
	Number INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Name TEXT NOT NULL,
	Type_1 TEXT NOT NULL,
	Generation INTEGER NOT NULL,
	Attack INTEGER NOT NULL,
	Defense INTEGER NOT NULL,
	Sp_Atk INTEGER NOT NULL,
	Sp_Def INTEGER NOT NULL,
	Speed INTEGER NOT NULL,
	HP INTEGER NOT NULL	
);



-- DROP TABLE IF EXISTS etudiant;

-- CREATE TABLE etudiant (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     prenom TEXT NOT NULL,
--     nom TEXT NOT NULL,
--     note INTEGER NOT NULL
-- );